Repository Max-ChenFei/VisualProgrammingEditor, pull requests merged in 2023-07, with the labels that each got.

#245 Fix/theme missing
  src/editor/VPEditor.css
  src/editor/VPEditor.tsx
  src/editor/gui/NodeLibraryList.css
  src/editor/gui/NodeLibraryList.tsx
  src/editor/hooks/useScene.ts
  src/editor/index.css
  src/editor/index.ts
  src/editor/utils/index.ts
  src/editor/utils/uniquePool.ts
  src/index.css
Labels: bug

#247 fix #233
  src/editor/gui/NodeLibraryList.tsx
Labels: bug

#248 Refresh the callback definition when the input data changes
  src/editor/gui/elements/SearchedTreeView.tsx
Labels: bug

#249 Keep consistent of the font size and logo in menu
  src/editor/gui/elements/Menu.tsx
  src/editor/gui/index.css
  src/editor/index.css
Labels: enhancement

#252 Fix color hints for connection
  src/editor/gui/ConnectionTip.tsx
  src/editor/gui/elements/StyledTreeItem.tsx
Labels: bug

#253 Update the title when change
  src/editor/components/nodes/CreateFunction.tsx
  src/editor/components/nodes/Return.tsx
Labels: bug

#261 Feat/serialization create var
  src/NodeTypeExtension/extension1/module1.json
  src/VPFileExample.json
  src/editor/Serializer.ts
  src/editor/components/nodes/CreateVariable.tsx
  src/editor/components/nodes/SetterNode.tsx
  src/editor/gui/GetterSetterMenu.tsx
Labels: bug

#262 Fix/ref node not update
  src/editor/components/nodes/FunctionCall.tsx
  src/editor/components/nodes/Return.tsx
  src/editor/hooks/useGraph.ts
  src/editor/hooks/useScene.ts
Labels: bug

#273 Feat/css enhancement
  package-lock.json
  package.json
  src/editor/components/handles/index.css
  src/editor/components/nodes/CreateVariable.tsx
  src/editor/components/nodes/StickyNoteNode.css
  src/editor/components/nodes/StickyNoteNode.tsx
  src/editor/components/nodes/index.css
  src/editor/gui/NodeLibraryItem.css
  src/editor/gui/NodeLibraryItem.tsx
  src/editor/gui/NodeLibraryList.css
  src/editor/gui/NodeLibraryList.tsx
  src/editor/gui/SearchMenu.tsx
  src/editor/gui/elements/SearchInput.tsx
  src/editor/gui/elements/StyledTreeItem.tsx
  src/editor/gui/index.css
  src/editor/index.css
  src/editor/widgets/InPlaceInput.tsx
  src/editor/widgets/WidgetFactory.tsx
  src/index.tsx
Labels: enhancement

#278 Fix comment move issue after pasting
  src/editor/types/Comment.ts
Labels: bug

#281 Clear the tooltips of the node
  src/NodeTypeExtension/extension1/module1.json
  src/NodeTypeExtension/extension2.json
  src/NodeTypeExtension/os.json
  src/VPLibraryExample.json
  src/editor/components/nodes/CreateFunction.tsx
  src/editor/components/nodes/FunctionCall.tsx
  src/editor/components/nodes/FunctionNode.tsx
  src/editor/components/nodes/GetterNode.tsx
  src/editor/components/nodes/Return.tsx
  src/editor/components/nodes/SetterNode.tsx
  src/editor/extension/buildin.json
  src/editor/gui/GetterSetterMenu.tsx
Labels: enhancement

#283 Fix wrong position of connection menu
  src/editor/hooks/useScene.ts
Labels: bug

#286 Feat/auto attach
  src/VPFileExample.json
  src/editor/VPPanelSetting.js
Labels: enhancement

#287 Fix serialization of sticky note
  src/editor/Deserializer.ts
  src/editor/Serializer.ts
Labels: bug

#288 Hardcode the miniwidth of the node resizer
  src/editor/components/nodes/StickyNoteNode.tsx
Labels: bug

#291 Fix nodes move in overlapped comments
  src/editor/hooks/useScene.ts
Labels: bug

#297 Fix/overlapped comments
  src/VPFileExample.json
  src/editor/Deserializer.ts
  src/editor/Serializer.ts
  src/editor/components/nodes/CommentNode.tsx
  src/editor/components/nodes/StickyNoteNode.tsx
  src/editor/hooks/useScene.ts
Labels: bug, enhancement

#302 Feat/auto layout
  package-lock.json
  package.json
  src/editor/VPEditor.tsx
  src/editor/VPPanelSetting.js
  src/editor/components/nodes/CommentNode.tsx
  src/editor/gui/SearchMenu.tsx
  src/editor/hooks/useGraph.ts
  src/editor/hooks/useScene.ts
  src/index.tsx
Labels: bug, enhancement

#304 Remove node version 16
  .github/workflows/build.yml
Labels: enhancement

#307 Add resize icon for comment node and sticky note
  src/editor/components/nodes/CommentNode.tsx
  src/editor/components/nodes/ResizeIcon.tsx
  src/editor/components/nodes/StickyNoteNode.tsx
Labels: css

#309 Fix/duplicate paste command
  src/editor/gui/SearchMenu.tsx
  src/editor/hooks/useScene.ts
Labels: bug

#310 Add new panel and icons
  src/editor/VPEditor.tsx
  src/editor/components/ControlPanel.tsx
  src/editor/components/Controls.tsx
  src/editor/components/index.ts
Labels: enhancement

#311 Feat/focus input when comment sticky note creation
  src/editor/Deserializer.ts
  src/editor/gui/SearchMenu.tsx
  src/editor/gui/elements/SearchInput.tsx
  src/editor/hooks/useKeyDown.ts
  src/editor/hooks/useScene.ts
  src/editor/widgets/InPlaceInput.tsx
  src/editor/widgets/InPlaceTextArea.css
  src/editor/widgets/InPlaceTextArea.tsx
Labels: enhancement

#317 disable input focus for function create node
  src/editor/components/nodes/CommentNode.tsx
  src/editor/components/nodes/CreateFunction.tsx
  src/editor/widgets/InPlaceInput.tsx
Labels: bug

#320 Fix undefined handle for function call
  src/editor/hooks/useGraph.ts
  src/editor/hooks/useScene.ts
Labels: bug

#321 Update the reactflow
  package-lock.json
  package.json
Labels: bug

#322 Fix/disable input focused
  src/editor/Deserializer.ts
  src/editor/components/nodes/CommentNode.tsx
  src/editor/components/nodes/StickyNoteNode.tsx
  src/editor/gui/SearchMenu.tsx
  src/editor/hooks/useKeyDown.ts
  src/editor/hooks/useScene.ts
  src/editor/types/Comment.ts
  src/editor/types/StickyNote.ts
  src/editor/util.ts
  src/editor/widgets/InPlaceTextArea.tsx
Labels: bug

#323 Add mouse move capture event to the root
  src/editor/VPEditor.tsx
  src/editor/hooks/useKeyDown.ts
  src/editor/hooks/useScene.ts
Labels: enhancement

#326 Fix/multiple key down with modifier
  src/editor/VPEditor.tsx
  src/editor/hooks/index.ts
  src/editor/hooks/useKeyDown.ts
Labels: bug

#328 Fix/weird marquee selection
  src/editor/hooks/useScene.ts
Labels: bug

#330 Fix unnecesssary keydown event
  src/editor/VPEditor.tsx
Labels: bug

#333 Temp solution for internel properties update
  src/editor/VPEditor.tsx
  src/editor/hooks/useGraph.ts
  src/editor/hooks/useScene.ts
Labels: bug

#334 Add keydown for nodes
  src/editor/VPEditor.tsx
Labels: bug

#329 Feat/search menu
  src/editor/VPEditor.tsx
  src/editor/gui/SearchMenu.tsx
  src/editor/gui/elements/SearchedTreeView.tsx
  src/editor/hooks/useScene.ts
  src/editor/hooks/useTrackMousePos.ts
  src/editor/util.ts
Labels: enhancement

#340 Feat/move delete to menu for handle
  src/editor/VPEditor.tsx
  src/editor/components/nodes/CreateFunction.tsx
  src/editor/components/nodes/Return.tsx
  src/editor/gui/HandleMenu.tsx
  src/editor/hooks/useScene.ts
Labels: enhancement

#341 Fix createFunction is called twice
  src/editor/gui/SearchMenu.tsx
Labels: bug

#342 wrong connection of exec handle of createFunction
  src/editor/hooks/useScene.ts
Labels: bug

#347 Add deletable option for handle
  src/editor/VPEditor.tsx
  src/editor/components/nodes/CreateFunction.tsx
  src/editor/components/nodes/Return.tsx
  src/editor/components/nodes/Sequence.tsx
  src/editor/extension/flowControl.json
  src/editor/gui/HandleMenu.tsx
  src/editor/hooks/useGraph.ts
  src/editor/types/Handle.ts
Labels: bug

#280 Feat/edge style
  src/editor/Deserializer.ts
  src/editor/components/handles/Handle.tsx
  src/editor/components/handles/index.css
  src/editor/components/nodes/CreateFunction.tsx
  src/editor/components/nodes/Return.tsx
  src/editor/hooks/useGraph.ts
  src/editor/index.css
  src/index.tsx
Labels: enhancement

#350 Fix/undefined error of create function&&widgets disappear
  src/VPFileExample.json
  src/editor/hooks/useScene.ts
Labels: bug

#366 Feat/code generation
  package-lock.json
  package.json
  src/NodeTypeExtension/extension1/__init__.json
  src/NodeTypeExtension/extension1/module1.json
  src/NodeTypeExtension/extension2.json
  src/NodeTypePackage.ts
  src/VPFileExample.json
  src/VPLibraryExample.json
  src/editor/Deserializer.ts
  src/editor/components/nodes/CreateFunction.tsx
  src/editor/components/nodes/CreateVariable.tsx
  src/editor/components/nodes/MakeLiteralNode.tsx
  src/editor/components/nodes/MathNode.tsx
  src/editor/components/nodes/Return.tsx
  src/editor/extension/LoadPackageToRegistry.ts
  src/editor/extension/buildin.json
  src/editor/extension/float.json
  src/editor/extension/flowControl.json
  src/editor/extension/functionAndvar.json
  src/editor/extension/log.json
  src/editor/extension/string.json
  src/editor/gui/GetterSetterMenu.tsx
  src/editor/hooks/useGraph.ts
  src/editor/hooks/useScene.ts
  src/editor/toposort.d.ts
  src/editor/types/SourceCodeExec.ts
  src/editor/types/index.ts
  src/index.tsx
Labels: enhancement

#367 Fix extraCommands missing
  src/editor/hooks/useScene.ts
Labels: bug

#368 Add the add new pin to math node
  src/editor/Deserializer.ts
  src/editor/components/nodes/MathNode.tsx
  src/editor/extension/float.json
  src/editor/extension/string.json
Labels: enhancement

#369 Feat/move datatype to buildin
  src/NodeTypeExtension/extension1/Level2/module2.json
  src/NodeTypeExtension/extension1/__init__.json
  src/VPFileExample.json
  src/VPLibraryExample.json
  src/editor/extension/functionAndvar.json
  src/editor/types/DataType.ts
  src/editor/widgets/WidgetFactory.tsx
Labels: enhancement

#370 Fix/handle style
  src/VPFileExample.json
  src/editor/components/handles/Handle.tsx
  src/editor/components/handles/index.css
  src/editor/components/handles/index.ts
  src/editor/components/nodes/CreateFunction.tsx
  src/editor/components/nodes/Return.tsx
  src/editor/hooks/useGraph.ts
  src/editor/index.css
  src/editor/types/DataType.ts
  src/editor/widgets/WidgetFactory.tsx
Labels: bug

#374 Feat/access to source code
  src/editor/VPEditor.tsx
  src/editor/components/handles/Handle.tsx
  src/editor/components/nodes/CreateFunction.tsx
  src/editor/components/nodes/CreateVariable.tsx
  src/editor/components/nodes/Return.tsx
  src/editor/gui/SearchMenu.tsx
  src/editor/hooks/useScene.ts
  src/editor/types/DataType.ts
  src/editor/widgets/WidgetFactory.tsx
Labels: enhancement

#375 To delete the edges before deleting the node
  src/editor/hooks/useGraph.ts
Labels: bug

#376 Fix undefined property of return node
  src/editor/components/nodes/Return.tsx
Labels: bug
